stages:
  - Test

Test:
  stage: Test
  image: hikiko999/pyats_python:python-3.10.12
  tags:
    - cisco-pyats
  script:
    - pyats run job job-runner.py --testbed-file ios_testbed.yml --html-logs
    - cp ~/.pyats .
  artifacts:
    paths:
      - ./.pyats