stages:
 - Alert

Alert:
  stage: Alert
  environment: Testing
  tags:
    - docker-webex
  image: alpine:latest
  variables:
    CHILD_FOLDER: webex_alert
  script:
    - apk add curl
    - export WEBEX_WEBHOOK=$WEBEX_WEBHOOK_VAR
    - export WEBEX_MESSAGE=$WEBEX_MESSAGE_VAR
    - chmod 755 $CHILD_FOLDER/webex_webhook.sh
    - $CHILD_FOLDER/webex_webhook.sh
