stages:
 - Alert

Alert:
  stage: Alert
  environment: Testing
  image: alpine:latest
  script:
    - apk add curl
    - export WEBEX_WEBHOOK=$WEBEX_WEBHOOK_VAR
    - export WEBEX_MESSAGE=$WEBEX_MESSAGE_VAR
    - chmod 755 ./webex_webhook.sh
    - ./webex_webhook.sh
